export const BANGLADESH_DISTRICTS = [
  "All",
  "Chittagong",
  "Mymensingh",
  "Netrokona",
  "Gaibandha",
  "Rangpur",
  "Joypurhat",
  "Naogaon",
  "Bogra",
  "Rajshahi",
  "Chapainawabganj",
  "Pabna",
  "Sherpur",
  "Jamalpur",
  "Gazipur",
  "Norsinghdi",
  "Kishoregonj",
  "Sunamganj",
  "Sylhet",
  "Maulvibazar",
  "Habiganj",
  "Chuadanga",
  "Jhenaidah",
  "Magura",
  "Jessore",
  "Narail",
  "Gopalganj",
  "Chandpur",
  "Barisal",
  "Khulna",
  "Satkhira",
  "Bagerhat",
  "Noakhali",
  "Jhalokati",
  "Khagrachhari",
  "Rangamati",
  "Bandarban",
  "Cox-s-bazar",
  "Borguna",
  "Pirojpur",
  "Dhaka",
  "Comilla",
  "Feni",
  "Lakshmipur",
  "Munshiganj",
  "Brahmanbaria",
  "Faridpur",
  "Sirajganj",
  "Tangail",
  "Kurigram",
  "Natore",
  "Thakurgaong",
  "Panchagarh",
  "Nilphamari",
  "Lalmonirhat",
  "Dinajpur",
  "Patuakhali",
  "Manikgonj",
  "Shariatpur",
  "Madaripur",
  "Narayanganj",
  "Rajbari",
  "Meherpur",
];

export const COMMITTEE_TYPES = [
  "All",
  "Central Committee",
  "District Committee",
  "University Unit",
  "Medical College Unit",
  "Ward Committee",
];
